###
GET http://localhost:8000/


###
GET http://localhost:8000/flight


###
GET http://localhost:8000/flight/63e902ee48d0d408a86f4968

###
DELETE  http://localhost:8000/flight/deleteFlight/63e56b0204bedd56be5661ba


###
POST http://localhost:8000/flight
Content-Type: application/json

{
"Name":"new flight"
}